[build]
  publish = "public"
  command = "npm install --legacy-peer-deps && npm run build"  # Add legacy-peer-deps flag during install

[build.environment]
  NODE_VERSION = "16"  # Ensure Node.js version is set correctly
